module.exports = {
  pop: 'Pop',
  jazz: 'Jazz',
  hiphop: 'Hip-Hop',
  rap: 'Rap',
  country: 'Country',
  electronic: 'Electronic',
  edm: 'EDM',
  dubstep: 'Dubstep',
  trap: 'Trap',
  dance: 'Dance',
  disco: 'Disco',
  reggae: 'Reggae',
  ambient: 'Ambient',
  soul: 'Soul',
  blues: 'Blues',
  rock: 'Rock',
  funk: 'Funk',
  alternate: 'Alternate',
  alt: 'Alternate',
  indie: 'Indie',
  chill: 'Chill',
  lofi: 'Lofi',
  classical: 'Classical',
  romantic: 'Romantic',
  baroque: 'Baroque',
  rnb: 'R&B',
  progressive: 'Progressive',
  contemporary: 'Contemporary',
  gaming: 'Gaming',
  sleepsounds: 'Sleep Sounds',
  charts: 'Charts',
  community: 'Community',
  podcast: 'Podcast',
  talkshow: 'Talk Show'
}
